#!/bin/bash

# Get list of intentionally installed packages
# Source: https://askubuntu.com/a/250530/1137361

(zcat $(ls -tr /var/log/apt/history.log*.gz); cat /var/log/apt/history.log) 2>/dev/null |
  egrep '^(Start-Date:|Commandline:)' |
  grep -v aptdaemon |
  egrep -B1 '^Commandline:'
